if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "INPUT_FILE and OUTPUT_FILE are required")
endif()

file(READ "${INPUT_FILE}" _manifest_hex HEX)
string(LENGTH "${_manifest_hex}" _manifest_hex_length)
if(_manifest_hex_length EQUAL 0)
    message(FATAL_ERROR "Plugin manifest file is empty: ${INPUT_FILE}")
endif()

set(_manifest_bytes)
set(_offset 0)
while(_offset LESS _manifest_hex_length)
    math(EXPR _remaining "${_manifest_hex_length} - ${_offset}")
    if(_remaining GREATER 32)
        set(_line_length 32)
    else()
        set(_line_length ${_remaining})
    endif()
    string(SUBSTRING "${_manifest_hex}" ${_offset} ${_line_length} _line)
    string(REGEX REPLACE "(..)" "0x\\1, " _line "${_line}")
    string(APPEND _manifest_bytes "    ${_line}\n")
    math(EXPR _offset "${_offset} + ${_line_length}")
endwhile()

set(_source "// SPDX-License-Identifier: MIT
// Generated by stdc_add_plugin_manifest. Do not edit.

#include <stdcorelib/plugin/plugin.h>

extern \"C\" STDC_DECL_EXPORT STDC_PLUGIN_METADATA_SECTION
    const unsigned char stdc_plugin_manifest[] = {
${_manifest_bytes}};
")

file(WRITE "${OUTPUT_FILE}" "${_source}")
