if(NOT DEFINED PLUGIN_IID OR PLUGIN_IID STREQUAL "" OR NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "PLUGIN_IID and OUTPUT_FILE are required")
endif()

if(DEFINED METADATA_FILE AND NOT METADATA_FILE STREQUAL "")
    file(READ "${METADATA_FILE}" _metadata)
    if(_metadata STREQUAL "")
        message(FATAL_ERROR "Plugin metadata file is empty: ${METADATA_FILE}")
    endif()
else()
    set(_metadata "{}")
endif()

string(JSON _metadata_type ERROR_VARIABLE _metadata_error TYPE "${_metadata}")
if(_metadata_error OR NOT _metadata_type STREQUAL "OBJECT")
    message(FATAL_ERROR "Plugin metadata must be a JSON object: ${METADATA_FILE}")
endif()

set(_escaped_iid "${PLUGIN_IID}")
string(REPLACE "\\" "\\\\" _escaped_iid "${_escaped_iid}")
string(REPLACE "\"" "\\\"" _escaped_iid "${_escaped_iid}")
set(_envelope "{\"iid\":\"${_escaped_iid}\",\"metadata\":${_metadata}}")

string(JSON _envelope_type ERROR_VARIABLE _envelope_error TYPE "${_envelope}")
if(_envelope_error OR NOT _envelope_type STREQUAL "OBJECT")
    message(FATAL_ERROR "Failed to generate the embedded plugin metadata envelope")
endif()

string(HEX "${_envelope}" _metadata_hex)
string(LENGTH "${_metadata_hex}" _metadata_hex_length)
set(_metadata_bytes)
set(_offset 0)
while(_offset LESS _metadata_hex_length)
    math(EXPR _remaining "${_metadata_hex_length} - ${_offset}")
    if(_remaining GREATER 32)
        set(_line_length 32)
    else()
        set(_line_length ${_remaining})
    endif()
    string(SUBSTRING "${_metadata_hex}" ${_offset} ${_line_length} _line)
    string(REGEX REPLACE "(..)" "0x\\1, " _line "${_line}")
    string(APPEND _metadata_bytes "    ${_line}\n")
    math(EXPR _offset "${_offset} + ${_line_length}")
endwhile()

set(_source "// SPDX-License-Identifier: MIT
// Generated by stdc_add_plugin_metadata. Do not edit.

#include <stdcorelib/plugin/plugin.h>

extern \"C\" STDC_DECL_EXPORT STDC_PLUGIN_METADATA_SECTION
    const unsigned char stdc_plugin_metadata[] = {
${_metadata_bytes}};
")

file(WRITE "${OUTPUT_FILE}" "${_source}")
